#version: "3.4"
#services:
#  dnscrypt-proxy.public.dappnode.eth:
#    build: .
#    image: "dnscrypt-proxy.public.dappnode.eth:0.1.0"
#    restart: unless-stopped

version: "3.5"
services:
  dnscrypt-proxy.dnp.dappnode.eth:
    build: .
    image: "dnscrypt-proxy.public.dappnode.eth:0.1.0"
    container_name: DAppNodeCore-dnscrypt-proxy.dnp.dappnode.eth
    restart: always
    networks:
      dncore_network:
        ipv4_address: 172.33.1.2
    logging:
      driver: journald

networks:
  dncore_network:
    external: true