version: "3.5"
services:
  bindv2.dnp.dappnode.eth:
    build: .
    image: "bindv2.dnp.dappnode.eth:0.1.0"
    container_name: DAppNodeCore-bindv2.dnp.dappnode.eth
    restart: always
    networks:
      dncore_network:
        ipv4_address: 172.33.1.2
    logging:
      driver: journald
networks:
  dncore_network:
    external: true
